lambdas:
  ocr_lambda:
    name: ocr_lambda
    function_name: ocr_lambda
    ecr_repository: ocr_lambda
    memory_size: 1024
    timeout: 30
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "OCR Lambda function for text extraction"
  
  bedrock_lambda:
    name: bedrock_lambda
    function_name: bedrock_lambda
    ecr_repository: bedrock_lambda
    memory_size: 2048
    timeout: 300
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "Bedrock AI Lambda for toxic clause analysis in contracts"
  
  test_lambda:
    name: test_lambda
    function_name: test_lambda
    ecr_repository: test_lambda
    memory_size: 512
    timeout: 60
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "Test Lambda function for development"

  test_ocr:
    name: test_ocr
    function_name: test_ocr
    ecr_repository: test_ocr
    memory_size: 512
    timeout: 60
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "Test OCR Lambda function for development"

  test_bedrock:
    name: test_bedrock
    function_name: test_bedrock
    ecr_repository: test_bedrock
    memory_size: 512
    timeout: 60
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "Test Lambda function for development"
