lambdas:
  ocr_lambda:
    name: ocr_lambda
    function_name: ocr_lambda
    ecr_repository: ocr_lambda
    memory_size: 1024
    timeout: 30
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "OCR Lambda function for text extraction"
  
  bedrock_lambda:
    name: bedrock_lambda
    function_name: bedrock_lambda
    ecr_repository: bedrock_lambda
    memory_size: 2048
    timeout: 300
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "Bedrock AI Lambda for toxic clause analysis in contracts"

  analysis_result_loader:
    name: analysis_result_loader
    function_name: analysis_result_loader
    ecr_repository: analysis_result_loader
    memory_size: 1024
    timeout: 30
    environment_variables:
      LOG_LEVEL: INFO
    cors_origins:
      - "*"
    description: "Analysis result loader Lambda function for text extraction"

